### ISSUE TITLE
How to get bottom navigation buttons and page numbers to stay permanently visible

### ISSUE THREAD

**Issue by mymuno** [webslides/WebSlides#100]
Hi all

I was wondering how can I get the buttons and page numbers (check attached 
![clipboard01](https://user-images.githubusercontent.com/32898901/31714559-af284386-b3f8-11e7-8822-967e394a2a1c.jpg)
image) on the bottom of the page to stay always visible.
Can you please help me?

Thank you!

**Comment by jlantunez** [comment]
Hi @mymuno,
![navigation-remove-opacity0](https://user-images.githubusercontent.com/2033183/31715006-764823b0-b402-11e7-9487-6fd74356bcdf.png)

You have to remove the opacity parameter inside the #navigation element.

**Comment by mymuno** [comment]
Hi @jlantunez 

Thanks!
