### ISSUE TITLE
[question] Configuration in one file.

### ISSUE THREAD

**Issue by maltitco** [webslides/WebSlides#102]
It is possible to create presentation configuration in one file?
I would like to specify in the file where the presentation location is supposed to retrieve the contents for the given slide.

**Comment by jlantunez** [comment]
Hi @maltitco, Can you be more specific? Thanks!

**Comment by maltitco** [comment]
Hi @jlantunez, an example determine content by using markdown files:
slides/
  00-Intro/
    00-slide1.md
    01-slide2.md
  01-Chapter1/
    00-slide1.md
    01-slide2.md

Would like to make a simple CMS for creating and managing a presentation list...

**Comment by jlantunez** [comment]
We don't have this feature in our roadmap for the moment. We would like to make a CMS, but it's really a challenge to be honest.
