### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by InfernapeXavier** [webslides/WebSlides#103]
I'm trying to add a background image using the bg class and keep getting scroll bars, how do I get rid of them?

**Comment by jlantunez** [comment]
Can you be more specific, please. Check out these examples https://webslides.tv/demos/media#slide=4

**Comment by InfernapeXavier** [comment]
I copied the code from the https://webslides.tv/demos/netflix-culture#slide=9 and edited it according to my needs and changed the photo, but i get Scroll Bars on that slide. I think it's because the image is big? Is there any way I can scale it to fit?
(I'm fairly new to HTML.)

**Comment by oleteacher** [comment]
Hey @InfernapeXavier  Away from my main computer for holidays but I fixed images months back using responsive css.

Maybe this will give you some ideas if you are new to HTML:

https://www.w3schools.com/css/css_rwd_images.asp

**Comment by InfernapeXavier** [comment]
Thank you so much!
