### ISSUE TITLE
getting the webslides navbar working

### ISSUE THREAD

**Issue by sheldrake** [webslides/WebSlides#108]
I've added a navbar per [the documentation](https://webslides.tv/demos/components#slide=8).

My navbar has five items, each designed to jump to a particular part of the presentation. I give a section an id:
`<section id="thegoodbit">`

And then this for the corresponding nav item 
```
<li>
<a href="#thegoodbit" title="the good bit">the good bit</a>
</li>
```
Nothing happens. Reckon I'm missing something, which is not surprising given that I'm a bit of an amateur in these parts :-) Thanks in advance.

**Comment by jlantunez** [comment]
Hi Philip,

You can't navigate between different slides using this method :(

**Comment by sheldrake** [comment]
That would be why it doesn't work then :-) Thanks @jlantunez for confirming that I wasn't going mad.

Can I take it from your answer that there is no way to navigate between different slides from the navbar? In which case, may I ask, what is the navbar for? It would seem odd I think if it was only for external links ... that's not a _navigational_ device imho.

**Comment by jlantunez** [comment]
WebSlides is a multipurpose framework. You can build [landings](https://webslides.tv/demos/landings), [portfolios](https://webslides.tv/demos/portfolios), and [longforms](https://webslides.tv/demos/longforms) ;)
