### ISSUE TITLE
How do I link to a specific slide?

### ISSUE THREAD

**Issue by sheldrake** [webslides/WebSlides#109]
Following the [navbar thread](https://github.com/webslides/WebSlides/issues/108), how do I link to a specific slide?
I recognise that the URL indexes in the browser address bar, eg,
`#slide=9`
But of course, for example, slide 9 becomes slide 10 when a new slide is inserted earlier in the 'stack'.
Thanks.

**Comment by jlantunez** [comment]
Check out [this index](https://webslides.tv/demos/components#slide=2)

**Comment by sheldrake** [comment]
I have been through these 120 slides about five times. I still cannot find an answer to my question. I'm guessing if there is a way you can point me to precisely the right resource? Apologies, but you can see I have done as much desk research as possible and only fell back here when that failed.

**Comment by jlantunez** [comment]
First of all, sorry for the inconvenience :( Unfortunately we don't have a solution for that problem right now. @Antonio-Laguna: Do you have any idea?
