### ISSUE TITLE
How to use with npm

### ISSUE THREAD

**Issue by avatarKid** [webslides/WebSlides#111]
I import project with  npm install WebSlides/webslides 
I using ES, babel and webpack to build project. How can I integration webslides ?

**Comment by Antonio-Laguna** [comment]
It is possible. Just npm install, the package is published: https://www.npmjs.com/package/webslides

**Comment by hiroppy** [comment]
@Antonio-Laguna Could you publish new version because this library is 1.4.2 in npm?

**Comment by Antonio-Laguna** [comment]
What are you missing?

**Comment by hiroppy** [comment]
Currently, GitHub has [1.5.0](https://github.com/webslides/WebSlides/releases/tag/1.5.0), but npm has [1.4.2](https://www.npmjs.com/package/webslides).

**Comment by Antonio-Laguna** [comment]
@hiroppy sorry for the delay, it's now published 1.5.0

**Comment by hiroppy** [comment]
Thanks!!
