### ISSUE TITLE
Is it possible to change the orientation of touch on mobile?

### ISSUE THREAD

**Issue by josejaguirre** [webslides/WebSlides#113]
Hello, I'm making a website, where I need to move the slides, up and down. When I use the application on mobile, I see that it makes the transition but to both sides, is there a way to tell the object that when the gesture is made up and down, change the slide? First of all, Thanks.

**Comment by displaynone** [comment]
Hi Jose

You have to think in content scrolling, if the screen is too small for the height of the content you won't let the user to see the whole slide.

Anyway, you can modify touch scrolling [here](https://github.com/webslides/WebSlides/blob/master/src/js/plugins/touch.js)
