### ISSUE TITLE
how to turn on longform format?

### ISSUE THREAD

**Issue by lsalsich** [webslides/WebSlides#114]
Love this project. But, I can't seem to identify the class or settings which will turn my existing slideshow into a longform. I can copy the longform demo, of course, but would love to understand a little more about what settings make a longform work. 

For example, https://webslides.tv/demos/ seems to scroll down smoothly like a longform. I would like to set up something similar. 

Thanks!

**Comment by jlantunez** [comment]
Hi @lsalsich,

This will give you a simple outline of how WebSlides works.

**Horizontal slideshow:**
```
<main role="main">
 <article id="webslides">
    <section> <!--section = slide -->
```
**Vertical slideshow:**
```
<main role="main">
  <article id="webslides" class="vertical">
    <section> <!--section = slide -->
```

**Longform (just remove: id="webslides") = webslides.tv/demos:**
```
<main role="main">
  <article>
    <section>
```
 **Longform (article) :**
```
<main role="main">
  <article>
    <section>
      <div class="wrap longform">
         <!--.wrap.longform (width:72rem=720px) = Better reading experience (90 characters per line) -->


```

**Comment by lsalsich** [comment]
Thanks very much!
