### ISSUE TITLE
Support for Vimeo Videos to auto play/stop on slide enter/exit

### ISSUE THREAD

**Issue by coldes** [webslides/WebSlides#117]
...a query - love the youtube api to auto play/stop on slide enter/exit using the webslide youtube api as per demos - any way this could/can work for Vimeo Videos?

**Comment by coldes** [comment]
...and once again, another github query that no one can be bothered to respond to

**Comment by jlantunez** [comment]
My bad! Sorry :(

WebSlides was made to be simple. When you build a product, you make decisions. We assume people prefer YouTube over Vimeo.
