### ISSUE TITLE
Integration with backend code

### ISSUE THREAD

**Issue by stccorp** [webslides/WebSlides#119]
I just discovered webslides today, so have 0 knowledge. I noticed all examples are a static html page . Could it possible to integrate webslides such that the slides come from a database? have some kind of hooks to allow that?  Something similar to the code shown bellow? Thank you 

Maybe something like

window.ws = new WebSlides();
window.ws.init({
  nextUrl: next_section(),
  previousUrl: prev_section()
});

function next_section(){
$.ajax({
          url: "ajax_get_next_section.php&current_slide=XX",
          type: "GET"
          success: function(data){
              $('#section_content').html(data);
          }
       });
}

**Comment by Antonio-Laguna** [comment]
Hi @stccorp, unfortunately, we don't have any way right now to support that. You'll have to have all the slides in beforehand for WebSlides to work.
