### ISSUE TITLE
Form elements look weird on css

### ISSUE THREAD

**Issue by stccorp** [webslides/WebSlides#120]
Is there are reason why form elements look weird(full screen , edge to edge)?  Can they be changed to look normal?

**Comment by stccorp** [comment]
I see. I have to create a container to fix the size , otherwise it goes full screen if I dont specify anything.  Take a look
![opera_2018-08-21_13-33-24](https://user-images.githubusercontent.com/8180135/44418768-442f1f00-a547-11e8-9779-4bbb62886950.png)

**Comment by jlantunez** [comment]
Use .size-50, .size-30...
