### ISSUE TITLE
Nested slides

### ISSUE THREAD

**Issue by liborw** [webslides/WebSlides#123]
Would it be possible to add nested slides? You can prepare slide for expected questions, or have the main topics in main slides and deeper explanation in the nested slides...

**Comment by jlantunez** [comment]
Hi Libor,

It's not possible and it's not a feature that's currently planned to be added. Thanks!

**Comment by McCodeman** [comment]
Would you accept user contribution to extend the framework to support this?

**Comment by Antonio-Laguna** [comment]
I think we would be open for the conversation on a high level base.
