### ISSUE TITLE
How to use slide counter

### ISSUE THREAD

**Issue by arthurgleckler** [webslides/WebSlides#130]
It must be obvious, but I can't figure out how to use the slide counter feature.  I don't see a counter on any of the demos, and when I add <nav role="navigation"> inside a <header>, it still doesn't appear.  Would someone please enlighten me?

Thanks, and thank you for WebSlides.  I just discovered it, and I've already been able to produce a much better-looking presentation than I ever have before.  It's absolutely wonderful.

**Comment by jlantunez** [comment]
Hi @arthurgleckler, 

Hover your mouse over the bottom center of the slide until the counter displays. Check out this gif. Thanks!

![counter-webslides](https://user-images.githubusercontent.com/2033183/52107115-6bf5d900-25f5-11e9-87cf-2896abc5ba02.gif)

**Comment by arthurgleckler** [comment]
Thank you.  I didn't see that because I wasn't in full-screen mode.  It doesn't appear otherwise for me in either Chrome or Firefox.
