### ISSUE TITLE
stop navigation on end

### ISSUE THREAD

**Issue by miezekathy** [webslides/WebSlides#182]
Hey,

is there a possibility to stop the navigation on the last slide in order to avoid an endless loop?

thank you!

**Comment by Antonio-Laguna** [comment]
@miezekathy have you tried to call it with `loop: false`?  You can find the options here: https://github.com/webslides/WebSlides/wiki/Core-API

**Comment by miezekathy** [comment]
@Antonio-Laguna thank you so much 🙏 it works!

**Comment by Antonio-Laguna** [comment]
I'm glad it did! Closing this issue then!
