### ISSUE TITLE
WebSlides Roadmap

### ISSUE THREAD

**Issue by jlantunez** [webslides/WebSlides#34]
Hi,

The roadmap aims to set out when certain features will appear.  Please contribute to WebSlides development :) https://github.com/jlantunez/webslides/projects/1

**Comment by ramon-src** [comment]
Hi @jlantunez can you change the "A new, better webslides.js architecture" card to an issue? I will reestruct little by little. My intention is first separate by comments all the script webslides, refactoring and after modularize it.

**Comment by jlantunez** [comment]
Hi @ramon-src,

Thanks for the suggestion. Done!
