### ISSUE TITLE
Mobile (only) transitions between the slides:

### ISSUE THREAD

**Issue by Belelros** [webslides/WebSlides#46]
- CSS: Two new animations: .slideInLeft (next slide) and .slideInRight (previous slide)
- JS: When you swipe to the previous slide, .js will add section.slideInRight

**Comment by Belelros** [comment]
Need to iterate this a bit further.

Do we add an option to opt-out of this feature?

@jlantunez @displaynone

**Comment by displaynone** [comment]
I would add some transition between slides. The fade effect can be simple.

Let the user select which transition wants, none or some effect.
