### ISSUE TITLE
Make autoslide a plugin

### ISSUE THREAD

**Issue by Belelros** [webslides/WebSlides#51]
Autoslide needs more logic than it currently has so it makes no sense to keep it inside the WebSlide core.

* We need to actually stop autosliding if the user focuses any focusable element

Somehow related. Should we give an option to disable looping? That is, not allowing to go to first slide from last one by triggering a next navigation and the same but with prev?

@jlantunez @displaynone

**Comment by displaynone** [comment]
I don't understand what you mean with "triggering a next navigation and the same but with prev". I assume it's necessary to trigger some event to stop looping, but what do you have in mind?

**Comment by jlantunez** [comment]
It seems that the autoslide feature is broken on [dev branch](https://github.com/webslides/WebSlides/tree/dev)
