### ISSUE TITLE
Move to SCSS with Autoprefixer

### ISSUE THREAD

**Issue by Belelros** [webslides/WebSlides#52]
In order to keep growing naturally, we want to transition to SCSS.

Things that should happen:

- [x] Ensure we use webpack but actually exporting a CSS file without needing to import the CSS  from JS. (Which is the Webpack way)
- [x] Use autoprefixer to remove all prefixes.
- [x] Current comments should be kept where they make sense and also in the output.
- [x] Separate in units as smaller as possible so it's clear where to look when needing to change something or add something.

**Comment by CKGrafico** [comment]
It is ok to you to add that structure? https://github.com/CKGrafico/Gulp-Boilerplates/tree/master/app/scss

**Comment by CKGrafico** [comment]
Doing

**Comment by CKGrafico** [comment]
[X]  Ensure we use webpack but actually exporting a CSS file without needing to import the CSS from JS. (Which is the Webpack way)
[X] Use autoprefixer to remove all prefixes.

**Comment by Belelros** [comment]
The structure you mentioned seems alright to me btw!

**Comment by jlantunez** [comment]
Thanks for contributing @CKGrafico! :)

**Comment by Belelros** [comment]
Can we please remove the generated files from the PR? It gets harder to review.

**Comment by CKGrafico** [comment]
We can do it on the last commit, I'm working on the code now

**Comment by CKGrafico** [comment]
-[x] Current comments should be kept where they make sense and also in the output.
Now is generating webslides.css and webslides.min.css

**Comment by CKGrafico** [comment]
I think that is enough for my side for this moment xD you have super big CSS files I think that is your turn to split it on multiple files I've ended my PR with this if is OK for you https://github.com/jlantunez/webslides/pull/53 (for a guy that hates webpack, not bad haha)

I suggest to you to use BEMIT or something similar if you want 
- https://github.com/CKGrafico/Gulp-Boilerplates/tree/master/app/scss
- http://blog.ckgrafico.com/tomando-decisiones-estructurar-los-componentes-css/ (ESP)

**Comment by CKGrafico** [comment]
Deleted non required files

**Comment by jlantunez** [comment]
Thanks so much @CKGrafico 👍

**Comment by CKGrafico** [comment]
Tell me if you need something else before approve the PR
