### ISSUE TITLE
Autoplay videos only on slide/section.current

### ISSUE THREAD

**Issue by jlantunez** [webslides/WebSlides#54]
WebSlides supports [full-screen videos](https://webslides.tv/demos/components#slide=101), but is not useful. We need autoplay videos only when you are watching the video. When you go to the next/prev slide, video (and sound) stops.

**Comment by Belelros** [comment]
@jlantunez should we add this same full-screen to YouTube as well? I think it'd be cool to have said integration and I could make this work too with YouTube. 

See an example here: https://codepen.io/dudleystorey/pen/PZyMrd

**Comment by jlantunez** [comment]
That would be very good. We are going to need invisible pause/play options (spacebar, presenter remote, mouse...?)

**Comment by Belelros** [comment]
Right now we don't offer any of those options to other videos. I think we could add some styles to offer a traditional youtube video that can be manually played. 

I assume this is only for background videos

**Comment by jlantunez** [comment]
Right! What is the difference between a background video and a fullscreen video?

At the same time, we have this [slide](https://webslides.tv/demos/components#slide=106) `section.fullscreen + .embed`

🤔

**Comment by jlantunez** [comment]
- Dev Branch: When the HTML5 video is out of view (not .current) doesn't actually pause. It only happens when you have 2 or more tabs open in Firefox with the same presentation.
