### ISSUE TITLE
PDF export would be awesome

### ISSUE THREAD

**Issue by tart2000** [webslides/webslides#61]
At the moment, using print > save as PDF only shows the active slide. 
It would be great if you could easily save your slideshow as a PDF also...

**Comment by jlantunez** [comment]
Hi Arthur, check out this plugin made by @jonashaefele: https://github.com/webslides/webslides/issues/5#issuecomment-287022002

**Comment by jlantunez** [comment]
Hi Arthur! We [have fixed the print issue](https://github.com/webslides/webslides/commit/373327b091dd7cc835f600b2832e04450ec7a73d
) in the development branch. Thanks for noticing!
