### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by ramusbucket** [webslides/WebSlides#64]
Does `<pre>` element provide syntax highlighting for different programming languages? could be a potential enhancement request...

**Comment by Belelros** [comment]
Hello, we don't currently provide any syntax highlighting and we don't currently plan to as explained in our wiki: https://github.com/webslides/WebSlides/wiki#can-you-add-this-new-feature

You can add whatever syntax highlighter you want.

Thanks for asking!

**Comment by ramusbucket** [comment]
Understood. Thank you very much for your prompt response!
