### ISSUE TITLE
Simple js to move to navigate between slide? 

### ISSUE THREAD

**Issue by tart2000** [webslides/WebSlides#65]
Hi! 
Is there a simple way to add nextSlide() or goToSlide('x') on a button to navigate between slides? 
Thank you

**Comment by Belelros** [comment]
Hey!

There sure is!. Please take a read [at our docs](https://github.com/webslides/WebSlides/blob/master/docs/technical.md). If you find that we expressed ourselves poorly please let us know!

You should be able to do `ws.goToSlide(2)` or `ws.goNext()`

**Comment by tart2000** [comment]
Thanks for the quick reply! 
I just looked into the wiki and components. 
I figured the 'technical' would be for 'hard stuff'. 
Cheers

**Comment by tart2000** [comment]
In case anyone ends up here wondering how to use it.
I just did: 
`<a href="#" class="button" onClick="ws.goNext()">Next</a>`

**Comment by sull** [comment]
can ```ws.goToSlide(2)``` use section IDs instead of index #?

**Comment by aminou7** [comment]
[download book best seo tools free](http://www.algeria-pedia.info/2017/04/download-book-best-seo-tools-free.html)

**Comment by Belelros** [comment]
It can't but it's actually a good idea. Can you open a separate issue @sull?

**Comment by sull** [comment]
sure
