### ISSUE TITLE
Is there a way to disable scrolling to the next screen: only go to next screen on key press

### ISSUE THREAD

**Issue by jfx1026** [webslides/WebSlides#66]
I don't know if this is the right place to ask this question, so I apologize up front if I am wrong.

I love Webslides, it's easy and awesome.

My client is putting a little too much on some screens and some of our users aren't super web savvy. They are scrolling wildly, and flying around the presentation.

Is there a way to disable the scroll to next screen functionality.
Users would be able to use the arrow keys and on screen links to get around.

**Comment by Belelros** [comment]
This is an interesting question.

We'll add an option to disable it but as a workaround in the meantime you can put this:

`WebSlides.registerPlugin('scroll', function(){});`

Before actually creating the WebSlides instance. So the full code should be (if you take it from one of our demos)

```html
<script src="static/js/webslides.js"></script>
<script>
  WebSlides.registerPlugin('scroll', function(){});
  window.ws = new WebSlides();
</script>
```

This will register a scroll plugin with an empty function which will effectively disable the scroll behaviour. Hope it helped!

**Comment by jfx1026** [comment]
Perfect! This helps a ton.

**Comment by Belelros** [comment]
Still like to offer a better way to this
