### ISSUE TITLE
Background Video responsive

### ISSUE THREAD

**Issue by hongzhou85** [webslides/WebSlides#68]
I would probably consider this as an issue as the video is compressed when used as background video. It is not responsive to zoom or focus on the video, maybe zoom in center or etc.

Current implementation makes the video goes out of proportion.

**Comment by jlantunez** [comment]
@hongzhou85 You're right! We will try [something like this](https://fvsch.com/code/video-background/) - Demo: https://fvsch.com/code/video-background/test.html Give us a few days to get this set up properly :)

**Comment by hongzhou85** [comment]
Exactly what I meant! Looking forward to it. It's an awesome project 👍
