### ISSUE TITLE
Background with multiple images

### ISSUE THREAD

**Issue by hongzhou85** [webslides/WebSlides#69]
I still figuring out how to have a background and an image at the bottom left corner together. There are examples with background align to bottom left, but I haven't found one with multiple images. Any idea?

**Comment by jlantunez** [comment]
This? 
![multiple-backgrounds](https://cloud.githubusercontent.com/assets/2033183/24560313/88521e16-1642-11e7-89e1-ee07c8044085.png) Maybe this post can help you: http://www.css3.info/preview/multiple-backgrounds/
