### ISSUE TITLE
Height incompatible with iphone Safari

### ISSUE THREAD

**Issue by hongzhou85** [webslides/WebSlides#70]
The footer and bottom aligned design are being "chopped" off in Safari browser on iphone (iphone 6s Plus).

This may be due to the bottom menu bar on safari.

**Comment by jlantunez** [comment]
Please send us a screenshot/url to see exactly where is the problem.

**Comment by hongzhou85** [comment]
http://glimpse.video/#slide=2

Could you check it out with safari on iphone?

**Comment by jlantunez** [comment]
Do you want the logo and the button perfectly aligned? Delete "float:none" (base. css - line 1268)
![aligns](https://cloud.githubusercontent.com/assets/2033183/24599418/64af4bc2-1850-11e7-93f1-cd7e7753f2d7.png) ![footer-align](https://cloud.githubusercontent.com/assets/2033183/24599477/a73129ac-1850-11e7-9872-3d0847f6d30f.png)

**Comment by hongzhou85** [comment]
Yes it's fine on chrome but the height is cut off on safari in iphone due to the menu bar at the bottom. Thanks I'll edit that.
