### ISSUE TITLE
ws.goToSlide() support of section ID in addition to slide index number

### ISSUE THREAD

**Issue by sull** [webslides/WebSlides#71]
I would find it useful to jump to slide based on section ID value instead of just slide index #.

`<section id="welcome">....</section>`

`<a href="#" class="button" onClick="ws.goToSlide("welcome")">Go to beginning</a>`

**Comment by sull** [comment]
I looked at how it's currently working and noticed that though no section IDs are used in the markup of the template, you do add section IDs to the dom once page is loaded (section-1, section-2 etc).

I was going to modify code but seeing this I decided to just implement the functionality outside of the core webslides.js. 

Something like...

`var sections = document.getElementsByTagName("section");`
`sections = Array.prototype.slice.call(sections)`

And then a wrapper function around ```ws.goToSlide```

`function goToSlideId(this_section_id) {
	index = sections.findIndex(function (x) { return x.accessKey == this_section_id })
	ws.goToSlide(index);
}`

Notice I am using "accessKey" attribute instead of "id" now since id was being used by the webslides already.

`<a href="#" class="button" onClick="goToSlideId('home')">go home</a>`

This seems ok until you decide if it's worth modifying core codebase to support this request..

**Comment by Belelros** [comment]
I'd want to give the option to use custom ids if preferred. That done then using goToSlideId on our end should be pretty straightforward. Thanks for The work you've put into this @sull

**Comment by eddy-ojb** [comment]
Has this been implemented? If so, I am really keen to see an example as I am not so familiar with javascript.

**Comment by eddy-ojb** [comment]
By an example, I meant a document so that I can scan through it! Thank you in advance.

**Comment by eddy-ojb** [comment]
I tried sull's method, which changes the html link in the address bar to e.g. "#home", however, the link does not execute. When I went to inspect the "home" section ID via Chrome "Inspect", it says that the "home" section id is "section-1".

How do I get around this?

**Comment by Antonio-Laguna** [comment]
Hey @eddy-ojb, unfortunately, I forgot about this and we didn't work on it on our last release. This is trivial. Hopefully, I can find some time soon and get this working.

**Comment by eddy-ojb** [comment]
Thank you Antonio. I am slowly learning html, css and js with your awesome software to move away from powerpoints. In the meantime, are you able to provide a work around example that I can follow? Perhaps in a couple of demo slides?

**Comment by Antonio-Laguna** [comment]
This got way forgotten, any link with `data-slide="X"`, `X` being any of the indexes, will navigate to the desired slide.
