### ISSUE TITLE
Slides Index

### ISSUE THREAD

**Issue by jlantunez** [webslides/WebSlides#73]
Thumbnails navigation gallery. You launch the slides index clicking on the counter.

**Comment by Belelros** [comment]
Hey @willykaram this has been an ongoing effort by @displaynone which is on the zoom branch which is basically the work you outline on point 3.

**Comment by jlantunez** [comment]
Hi @willykaram! Thanks for your detailed suggestions :)

**Comment by willykaram** [comment]
@Belelros thanks for pointing me to that branch. I read through all the open/closed issues, but forgot to check out the other branches. I'll review that to see how I can assist and perhaps try and contribute solutions for #1 & #2 above, which dovetail with the work that @displaynone is doing.
