### ISSUE TITLE
Horizontal sliding

### ISSUE THREAD

**Issue by justinpezzack** [webslides/WebSlides#77]
Is there a way to slide horizontally? or just vertical and fade? would be a cool feature.

**Comment by jlantunez** [comment]
Hi @justinpezzack, 

Just remove class="vertical" in the `#webslides` element. Check out these demos: https://webslides.tv/demos/landings - https://webslides.tv/demos/netflix-culture

**Comment by justinpezzack** [comment]
@jlantunez awesome thanks!
