### ISSUE TITLE
Content hidden behind header

### ISSUE THREAD

**Issue by balaji-embedcentrum** [webslides/WebSlides#80]
Hi,
This is an awesome slide show. I am trying to use it as a full fledged website incl. header and navigation. My problem is:
1) With the suggestion from one issue, I am able to make it fixed header
2) But, the content is getting hidden(first 2 lines, if I see in mobile view; Bigger screens are ok) behind the header.

Do you have a suggestion on this? Thank you.

**Comment by jlantunez** [comment]
Hi Balaji,

go to base.css and edit the padding-top of `section,.slide`: padding: 12rem 2.4rem 2.4rem;

![slide-padding-top](https://cloud.githubusercontent.com/assets/2033183/25573664/dd988532-2e47-11e7-8e20-dc393494b709.png)

**Comment by balaji-embedcentrum** [comment]
Perfect, worked Thank you.
