### ISSUE TITLE
Latest download in README isn't the latest

### ISSUE THREAD

**Issue by chrislopresto** [webslides/WebSlides#85]
I just pulled down the latest using the README link but realized it was 1.3.0 rather than 1.3.1:

![image](https://user-images.githubusercontent.com/93691/27519155-f6419fd4-59bb-11e7-92d2-40a7a65d3444.png)

No biggie, I just downloaded the latest from the releases page. Just wanted to let folks know.

**Comment by jlantunez** [comment]
Hi Chris, 

Thanks for noticing! Fixed :)
