### ISSUE TITLE
A way to delay fadeIn of text

### ISSUE THREAD

**Issue by marathon67** [webslides/WebSlides#89]
Thanks a lot for your WebSlides. I use it to present the drawing of pupils and I had like to display text on the pictures only after, for example, 5 seconds. Is a (relatively simple) way to achieve that ?

**Comment by jlantunez** [comment]
Hi,

just add the class ".slow". `<h2 class="fadeIn slow">Text</h2>`

Check out this example: [markup](https://webslides.tv/demos/components#slide=119)

**Comment by marathon67** [comment]
Hi José Luis


Thanks for your answer. But... my demand is not on having a longer duration of the fading effect, but of delaying the apparition of the text on the fullscreen image. Either by having a real automated delay or displayng the text only after un click or keyboard input.


Bien cordialement.

[http://formation.crdp-strasbourg.fr/webdoc/photos_atelier/logo_mail.jpg]

Pierre Kessler
Directeur Projets Numériques
Direction territoriale Grand Est
Académies de Nancy-Metz, Reims et Strasbourg
---
pierre.kessler@reseau-canope.fr
23 rue du Maréchal Juin
T. 03 88 45 50 42 ou 06 07 34 87 17
CS 20279 67007 Strasbourg Cedex
FRANCE

________________________________
De : José Luis Antúnez <notifications@github.com>
Envoyé : vendredi 21 juillet 2017 14:47
À : webslides/WebSlides
Cc : KESSLER Pierre; Author
Objet : Re: [webslides/WebSlides] A way to delay fadeIn of text (#89)


Hi,

just add the class ".slow". <h2 class="fadeIn slow">Text</h2>

Check out this example: markup<https://webslides.tv/demos/components#slide=119>

-

**Comment by jlantunez** [comment]
Try something like [this](http://www.chrisbuttery.com/articles/fade-in-fade-out-with-javascript/)
