### ISSUE TITLE
Feature idea : picture gallery 

### ISSUE THREAD

**Issue by tart2000** [webslides/WebSlides#90]
It would be pretty awesome to have a nice way of fitting 3 to 5 images on a slide... 
Or maybe you have a way to do it simply? 
Thank you.

**Comment by jlantunez** [comment]
You can do it in different ways :)

- [`ul class="flexblock gallery"`](https://webslides.tv/demos/components#slide=44) + [`.overlay`](https://webslides.tv/demos/components#slide=45)
- `img class="alignleft"`, `img class="alignleft size-80"`, [`img class="alignright size-50"`](https://webslides.tv/demos/components#slide=24)...
- `<div class grid><div class="column"><img class="aligncenter"></div></div>`
- Logos (clients): [`ul class="flexblock clients"`](https://webslides.tv/demos/media#slide=13)

**Comment by tart2000** [comment]
Thanks @jlantunez 
I'll try the different options. I'm basically looking to do something clean without having to resize all the different pictures, like this:  
![pre_590](https://user-images.githubusercontent.com/3958576/29165133-10ac6c3a-7dc2-11e7-9496-99fc8f1c854b.jpg)
