### ISSUE TITLE
presenter notes or presenter console?

### ISSUE THREAD

**Issue by c0b** [webslides/WebSlides#91]
like reveal.js or [`hovercraft`](http://regebro.github.io/hovercraft/#/step-1) support by key 'P' to open presenter notes in a separate screen,

presenter notes screen should have:

1. show presenter notes which do not show on the main screen
2. thumbnail of current slide, next slide
3. a wall clock for time, and a timer of how much time passed since beginning

**Comment by jlantunez** [comment]
Thanks for your suggestion, @c0b. It's a useful feature. Right now we're focused on building a simple platform to share stories. At the moment, presenter notes aren't in line with our product vision.

**Comment by c0b** [comment]
it's ok to keep in mind for later; but why close so early; or would you reopen later

**Comment by jlantunez** [comment]
It's not one of our priorities for the next months. Like you said we can always reopen later :)
