### ISSUE TITLE
Searching in a presentation

### ISSUE THREAD

**Issue by davidgardenier** [webslides/WebSlides#97]
By using "f" to go full-screen, it removes the option to easily search through a presentation with "ctrl+f" -
 perhaps there's a way to avoid that from happening? Additionally, while searching for a keyword does search through an entire presentation, it doesn't allow you to jump to any detection beyond the current slide. This would however be a brilliant feature to have, as it would allow you to jump through a presentation to the right slide upon getting a question about a particular word or phrasing on one of your previous slides. That being said - I'm loving webslides so far!

**Comment by Belelros** [comment]
Hi @davidgardenier thanks for taking the time to report this issue.

You're right, we should avoid going to presentation mode if we're searching either with Ctrl or Command. The other part sounds tricky but it sounds like an interesting challenge. Will take a look to see if we have any options there.

Will keep you posted ;)
